### ISSUE TITLE
How can I collect video links of a course automatically?

### ISSUE THREAD

**Issue by marykauf** [22nds/treehouse_video_downloader#1]
Hi
I wanna use your great downloader but the very first problem which I deal with is how to find links. As you know better it should be sub-links of each course not the course's link itself.
Can you please guide me how to collect courses links entirely at once?
At the end, is it possible to add a feature like downloading whole a 'track' just by providing its link?

**Comment by 22nds** [comment]
Hi  @marykauf 

Let me guide you through the steps. 
1. Go to the web page of the desired Treehouse course, for example: `https://teamtreehouse.com/library/introduction-to-html-and-css`
2. If you use Firefox: Open the console in Dev tools and go to Console tab. It is similar in Chrome. 
3. Enter `$$('.steps-list li a').forEach(a => console.log(a.href))` in the console and all links to videos will be displayed. 
4. Next copy the links to a text file and remove/replace the quotes (")

Now you can download the videos with the downloader.

**Comment by marykauf** [comment]
Thanks @22nds 
It worked.
What about downloading SRT subtitles/captions? Is there any way?

**Comment by 22nds** [comment]
Hi @marykauf,

I have now added code to be able to save only course and workshop URLs in the links file and the script will download all videos. 

In addition there is now a variable `SUBTITLES `in `main.py` where you can manage subtitle downloads. Just change it to `True' and it will download the .srt files. 

Let me know if you experience any issues. 

Best,
Maja

**Comment by marykauf** [comment]
Hi @22nds,

Just surprised! It works like a charm! 
You've added two great features plus a nice work on organization of courses content just in less than a day.
Congrats on your talent and thanks for your great support of repositories.

As a final request, is there any chance on adding a feature like downloading whole of a track or library by using its URL? Should be possible but I personally think it need much more energy and take more time to implement. I hope you add it as soon as possible.

Thanks,
Mary Kaufman

**Comment by 22nds** [comment]
Hi Mary, 

Thanks a lot for your feedback and I am sure you can learn all this on Treehouse - I have started there with python courses last year and built this downloader after few months. Just think of something you would like to have and then build it. 

For the track download I would suggest you use `$$('a.card-box').forEach( a => console.log(a.href));` on the track page (for example 'https://teamtreehouse.com/tracks/learn-python'). Then copy the links to `links.txt` and you are set. 

I won't be implementing this feature for now. 

Best,
Maja
