### ISSUE TITLE
Probably a bug

### ISSUE THREAD

**Issue by Sevana93** [22nds/treehouse_video_downloader#10]
Hi

I can't download [this course](https://teamtreehouse.com/library/build-a-weather-app-4) completely. Actually, **stage6** / **Video1** is the last video part which can be downloaded using your script. Please check it out.

Credential info (pro subscription) has been sent to your Email address.

Regards

**Comment by Sevana93** [comment]
Any help would be appreciated.

**Comment by 22nds** [comment]
Hi @Sevana93,

I have now tested the download with you credentials and was able to transfer all videos without errors. Make sure your youtube_dl is updated and try again. Unfortunately I don't have any other more useful advice. 
```
sudo -H pip install --upgrade youtube-dl
# or if you are using pip3
sudo -H pip3 install --upgrade youtube-dl
```

Kind regards,
22nds

**Comment by Sevana93** [comment]
Thanks for that critical advice,
I have just upgraded dependencies using the above command.
It should be solved.
