### ISSUE TITLE
Incomplete downloading when SUBTITLE variable is True

### ISSUE THREAD

**Issue by marykauf** [22nds/treehouse_video_downloader#2]
Hi

Unfortunately, just when SUBTITLE variable is true the problem encountered. It downloads only two or three files for most of the courses and suddenly go to next one. 

Log is attached.

[log.txt](https://github.com/22nds/treehouse_video_downloader/files/1220966/log.txt)

**Comment by 22nds** [comment]
Hi @marykauf

I have tested all 4 tracks you have in the log and I cannot reproduce the error. On my side it worked without issues. Can you make sure you have added `SUBTITLES = True`. I'll keep testing this and hopefully somehow encounter the issue myself.

**Comment by marykauf** [comment]
Hi @22nds 

I'm sure this variable causes the problem. Whenever I turn it false everything works fine. 

Please watch this short video. (I use your script on my VPS)

http://www.mediafire.com/file/1au401gnuubzbbl/screen.zip

**Comment by marykauf** [comment]
I sent you correct URL via Email.

**Comment by 22nds** [comment]
@marykauf  Thanks for the video! It is obvious that subtitles have issues on your computer but as I have said, I cannot recreate it on my Linux computer so it is impossible for me to start writing possible solutions. I will also look into this on my Windows machine - if maybe OS is the issue (first thing in the morning).

**Comment by marykauf** [comment]
@22nds I want to thank you for all the support and concern.

I appreciate your unbelievable support.

**Comment by marykauf** [comment]
Hi @22nds 

I've just downloaded '.webm' files of all courses which I want.    

If you think it is impossible to discover the exact reason of this problem, give an alternative chance that is saving only captions files. Let me know if it is possible to download .srt caption files only.

Thanks

**Comment by anh0d4** [comment]
I got the same issue!
When I set SUBTITLE = True, some of my course is interupted. I think it can't get subtitle file, sometime.
SUBTITLE = False, working well.
plz fix it,
Thank you. Love your work <3

**Comment by 22nds** [comment]
Hi @marykauf and @anh0d4,
 
I think I have identified the issue - question marks in the names of the srt files. I am already working on the solution. 

Best,
Maja

**Comment by 22nds** [comment]
Hi @marykauf and @anh0d4,

I have updated the code and it now rewrites the filename so Windows OS won't have issues with ? and other special characters.

If you would like to download only subtitles, you can comment out the line `# ydl.download([videolink])` and only subtitles will be downloaded. `SUBTITLE = True` must also be set :)
