### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by renegenoa** [22nds/treehouse_video_downloader#3]
OS: Windows7
TeamTreehouse Pro (trial account)
youtube-dl version 2017.08.13
beautifulsoup4 4.6.0
requests version 2.18.1

I have downloaded youtube-dl, beautifulsoup4, requests and treehouse_video_downloader. 
I have placed them under D:\treehouse.  
Added Username and Password for Treehouse in the **_main.py_** file.
Have tried with both subtitles True as well as false.
I am running the program through cmd
`D:\treehouse> python main.py`
It shows the files downloading and also the corresponding sub-folders are created in the folder, but they are all empty. Nothing is getting downloaded. 
Treehouse username ans password work fine, I can login and download with IDM but this program is not working for some reason.

Plz any help is appreciated.

**Comment by 22nds** [comment]
Hi @renegenoa!

Probably the issue is that you have downloaded the dependencies, but didn't install them.

Let's see if you have all of them installed. 
- First check youtube-dl. Write in your console:
```
youtube-dl --version
```
It should return youtube-dl version e.g. `2017.07.30.1` or newer. If you don't get the version written out (I would almost bet you will get nothing or error) run command to install youtube-dl `pip install youtube_dl`. If you get errors because permissions use `sudo pip install youtube_dl`. 

You can also check python modules to make sure they are installed. Use: 
```
python -c "import bs4" && echo $?
python -c "import requests" && echo $?
```
But as you mentioned the script is working (creating folders...) so these both should return `0`.

Let me know if you managed to resolve the issue!

**Comment by renegenoa** [comment]
HI @22nds! Thnx for your reply.

I had previously downloaded youtube-dl.exe for windows from the gitpage and had placed it under a folder of the same name in Program Files  and set the PATH variables. I tried to download the videos but it failed as it was only downloading the sample videos and no subs. The program was unable to use my login credentials for the Trial account.

I deleted the existing youtube-dl folder and also the path. 

I have created a new folder D:\Treehouse and have installed all the dependencies as mentioned in the gitpage and also placed the content of treehouse_video_downloader-master

**Comment by 22nds** [comment]
@renegenoa 

Can you doublecheck the username and password? If it is downloading only sample videos the username/password is not correct.

**Comment by renegenoa** [comment]
Hi **@22nds!**

The login credentials are working fine and I am able to log in to https:\\teamtreehouse account and view the complete individual videos and also download them using IDM.
I have tried using the username and password with "" as well as '' and also without any quotes in the **main.py**. When using the credentials without quotes it is giving ERROR: _not defined_
If you want I can PM you the login credentials, so that you can check it at your end.

**Comment by renegenoa** [comment]
Hi @22nds!

I was able to resolve the issue :)
The problem was with the links. I was using the links from individual videos. e.g instead of using `https://teamtreehouse.com/library/reporting-with-sql` I was using all the links to individual videos such as:
https://teamtreehouse.com/library/reporting-with-sql/working-with-text/-finding-the-length-of-text
https://teamtreehouse.com/library/reporting-with-sql/working-with-text/changing-the-case-of-text-columns
```
https://teamtreehouse.com/library/creating-excerpts-from-text
https://teamtreehouse.com/library/reporting-with-sql/working-with-text/replacing-portions-of-text
https://teamtreehouse.com/library/reporting-with-sql/working-with-text/practice-session
https://teamtreehouse.com/library/reporting-with-sql/aggregate-and-numeric-functions/counting-results
https://teamtreehouse.com/library/reporting-with-sql/aggregate-and-numeric-functions/counting-groups-of-rows
https://teamtreehouse.com/library/reporting-with-sql/aggregate-and-numeric-functions/getting-the-grand-total
https://teamtreehouse.com/library/reporting-with-sql/aggregate-and-numeric-functions/calculating-averages
```
As a result, nothing was downloaded. When I used the main course page `https://teamtreehouse.com/library/reporting-with-sql` as the download link everything worked like a charm. Even the subtitles worked! 

**Its a gem of a program!!!!** Keep up the good work.

**Comment by 22nds** [comment]
@renegenoa I'm so glad you found the sulution. I didn't even think that this might be the issue ;)
