### ISSUE TITLE
use external downloader like aria2c

### ISSUE THREAD

**Issue by renegenoa** [22nds/treehouse_video_downloader#4]
Hi **22nds!**

Is it possible to implement external downloader option such as aria2c that is used by youtube-dl.
`--external-downloader aria2c`.
Currently my dl speed averages at 50k/s, where as ISP speed is 100mbps. Multi-Threaded downloading will help a lot.

Regards
Rene

**Comment by 22nds** [comment]
@renegenoa Yes, I can do that today. I'll let you know when it is implemented.

**Comment by renegenoa** [comment]
Gr8 to hear that! Hope I will be able to contribute towards the development, but you are doing a great job here.
Just my 2cents - can we use this code in **main.py** (source: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L117-L265)
```
# Youtube-dl options
            options = {
                'external_downloader': aria2c
                'outtmpl': output
                # ,'verbose': True
            }
```

**Comment by 22nds** [comment]
@renegenoa Feel free to test it. aria2c is now the default option. Thanks for the suggestion!

**Comment by renegenoa** [comment]
Wow, that was fast! Appreciate it.
I have another question: 
So, it means that, if we want to implement any feature of youtube-dl into TVD we can use the method outlined by you under `# Youtube-dl options` in **main.py** and customize the options. Am I correct?
If that is corrrect then you should mention this under the **Usage section** so that others can benefit from the customization options. 
This is a nice piece of code. Love it!
Thnx a lot for your efforts.

**Comment by 22nds** [comment]
@renegenoa  Yes, you can upgrade the script by adding options in the options variable. You can see the list of all options here: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L129-L290 but some of them might not work - I know I had to implement authentication differently as youtube-dl didn't support it for Treehouse.  I'll add a comment in the Readme file :) Thx!
