### ISSUE TITLE
How to download MP4 Format

### ISSUE THREAD

**Issue by vinayvardhan999** [22nds/treehouse_video_downloader#5]
Hello,

The script is downloading webm format by default, I need to download mp4 format. Please tell what changes need to be done.

Thanks.

**Comment by vinayvardhan999** [comment]
Replace 
_**videolink = tag.source['src']**_
with
_**videolink = []
videolink = tag.find_all(type="video/mp4")[0].get('src')**_

**Comment by 22nds** [comment]
You could also add `'format': 'mp4'` to the options (after external_downloader) and replace `ydl.download([videolink])` with `ydl.download([video])`

**Comment by vinayvardhan999** [comment]
Its just my opinion, Please change the code so that default format will be mp4. As mp4 is better than webm and it can be viewed across all devices and compatible with all players.

**Comment by 22nds** [comment]
I'll put that to the list for the next update (when I have the access for treehouse again). Thanks!

**Comment by 22nds** [comment]
btw, the source code was updated and now has mp4 video format as the default + option to change it to webm.
